CREATE TABLE ANALISES_PERDAS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_analise TIMESTAMP,
    potencial_toneladas NUMBER(12, 2),
    colhido_toneladas NUMBER(12, 2),
    preco_tonelada NUMBER(10, 2),
    perda_toneladas NUMBER(12, 2),
    perda_percentual NUMBER(5, 2),
    prejuizo_financeiro NUMBER(15, 2),
    observacoes_checklist VARCHAR2(500)
);